<script setup>
import { computed } from 'vue';
import { Head, router } from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import CategoryIcon from '@/Components/CategoryIcon.vue';
import DynamicIcon from '@/Components/DynamicIcon.vue';
import Money from '@/Components/Money.vue';
import StatCard from '@/Components/StatCard.vue';
import { monthly as monthlyReport } from '@/routes/reports';
import { pdf as monthlyPdf } from '@/routes/reports/monthly';

const props = defineProps({
    year: { type: Number, required: true },
    month: { type: Number, required: true },
    periodLabel: { type: String, required: true },
    currencies: { type: Array, required: true },
});

const goToMonth = (year, month) => {
    router.get(monthlyReport.url({ query: { year, month } }));
};

const previousMonth = () => {
    props.month === 1 ? goToMonth(props.year - 1, 12) : goToMonth(props.year, props.month - 1);
};

const nextMonth = () => {
    props.month === 12 ? goToMonth(props.year + 1, 1) : goToMonth(props.year, props.month + 1);
};

const pdfUrl = computed(() => monthlyPdf.url({ query: { year: props.year, month: props.month } }));
</script>

<template>
    <Head title="Monthly report" />

    <AuthenticatedLayout>
        <template #header>
            <div class="flex flex-wrap items-center justify-between gap-3">
                <h2 class="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-200">
                    Monthly report
                </h2>
                <div class="flex items-center gap-2">
                    <button type="button" class="rounded-lg p-2 text-gray-500 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700" @click="previousMonth">
                        <DynamicIcon name="chevron-right" class="h-4 w-4 -scale-x-100" />
                    </button>
                    <span class="min-w-[9rem] text-center text-sm font-medium capitalize text-gray-700 dark:text-gray-300">{{ periodLabel }}</span>
                    <button type="button" class="rounded-lg p-2 text-gray-500 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700" @click="nextMonth">
                        <DynamicIcon name="chevron-right" class="h-4 w-4" />
                    </button>
                    <a :href="pdfUrl" target="_blank" class="ms-2 inline-flex items-center gap-1.5 rounded-lg bg-primary-600 px-3 py-2 text-sm font-medium text-white hover:bg-primary-700">
                        <DynamicIcon name="arrow-down-tray" class="h-4 w-4" />
                        Export PDF
                    </a>
                </div>
            </div>
        </template>

        <div class="mx-auto max-w-5xl space-y-8 px-4 py-8 sm:px-6 lg:px-8">
            <div v-for="currencySummary in currencies" :key="currencySummary.currency" class="space-y-6">
                <h3 v-if="currencies.length > 1" class="border-t border-gray-200 pt-6 text-sm font-semibold uppercase tracking-wide text-gray-400 dark:border-gray-700">
                    {{ currencySummary.currency }}
                </h3>

                <div class="grid grid-cols-2 gap-4 sm:grid-cols-3">
                    <StatCard label="Income" icon="arrow-up-circle" icon-color="text-green-600 dark:text-green-400" icon-bg="bg-green-50 dark:bg-green-500/10">
                        <Money :amount="currencySummary.income" :currency="currencySummary.currency" />
                    </StatCard>
                    <StatCard label="Expenses" icon="arrow-down-circle" icon-color="text-red-600 dark:text-red-400" icon-bg="bg-red-50 dark:bg-red-500/10">
                        <Money :amount="currencySummary.expense" :currency="currencySummary.currency" />
                    </StatCard>
                    <StatCard label="Savings" icon="chart-pie">
                        <Money :amount="currencySummary.savings" :currency="currencySummary.currency" />
                        <template #footer>{{ currencySummary.savingsRate.toFixed(1) }}% savings rate</template>
                    </StatCard>
                    <StatCard label="Fixed expenses" icon="arrow-path">
                        <Money :amount="currencySummary.fixedExpense" :currency="currencySummary.currency" />
                        <template #footer>generated by recurring transactions</template>
                    </StatCard>
                    <StatCard label="Variable expenses" icon="wallet">
                        <Money :amount="currencySummary.variableExpense" :currency="currencySummary.currency" />
                    </StatCard>
                    <StatCard label="Current net worth" icon="banknotes">
                        <Money :amount="currencySummary.netWorth" :currency="currencySummary.currency" />
                    </StatCard>
                </div>

                <div v-if="currencySummary.highlights.length > 0" class="rounded-xl border border-primary-100 bg-primary-50/60 p-5 dark:border-primary-500/20 dark:bg-primary-500/5">
                    <h3 class="mb-2 text-sm font-semibold text-primary-800 dark:text-primary-300">Monthly analysis</h3>
                    <ul class="space-y-1 text-sm text-gray-700 dark:text-gray-300">
                        <li v-for="(line, index) in currencySummary.highlights" :key="index" class="flex gap-2">
                            <span class="text-primary-500">&bull;</span>{{ line }}
                        </li>
                    </ul>
                </div>

                <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800">
                    <h3 class="mb-4 text-sm font-semibold text-gray-700 dark:text-gray-200">Expense breakdown by category</h3>
                    <p v-if="currencySummary.expenseByCategory.length === 0" class="py-8 text-center text-sm text-gray-400">
                        No expenses recorded in this period.
                    </p>
                    <div v-else class="space-y-3">
                        <div v-for="row in currencySummary.expenseByCategory" :key="row.category?.id ?? 'uncategorized'">
                            <div class="mb-1 flex items-center justify-between text-sm">
                                <span class="flex items-center gap-2 text-gray-700 dark:text-gray-300">
                                    <CategoryIcon v-if="row.category" :category="row.category" size="h-6 w-6" />
                                    {{ row.category?.name ?? 'Uncategorized' }}
                                </span>
                                <span class="font-medium text-gray-900 dark:text-white">
                                    <Money :amount="row.total" :currency="currencySummary.currency" /> ({{ row.percentage.toFixed(1) }}%)
                                </span>
                            </div>
                            <div class="h-1.5 w-full overflow-hidden rounded-full bg-gray-100 dark:bg-gray-700">
                                <div class="h-full rounded-full" :style="{ width: row.percentage + '%', backgroundColor: row.category?.color ?? '#6b7280' }"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </AuthenticatedLayout>
</template>
